### ISSUE TITLE
Minor spelling correction.

### ISSUE THREAD

**Issue by daryn987** [DartLazer/WhoIsHomeUI#11]
./WhoIsHomeUI/mysite/whoishome/templates/whoishome-->

network_timeline.html line 22 reads "Afer" should probably be "After"
view_host.html line 127 reads "Afer" should probably be "After"

I'm not a Git guru, so uncertain how to do a pull request. Neat project, thanks for sharing!

**Comment by DartLazer** [comment]
Fixed in last commit!

Thanks for mentioning it @daryn987 !
