### ISSUE TITLE
New Feature: Timeline graph

### ISSUE THREAD

**Issue by DartLazer** [DartLazer/WhoIsHomeUI#12]
Been thinking about how to implement a timeline graph for quite a while and I came up with the following using chartjs and chartjs-timeline

Desktop:
![afbeelding](https://user-images.githubusercontent.com/71255041/184942422-64146adb-62d4-4f5d-8581-caaa2a28f85d.png)

Mobile:
![afbeelding](https://user-images.githubusercontent.com/71255041/184942639-8f451fe6-e530-41e9-8c84-f02544a1cdfa.png)

I'd like to hear some feedback and see what you guys think of it @babanomania @spandan13
You can hover over with your mouse and it will show the times etc:

![afbeelding](https://user-images.githubusercontent.com/71255041/184942798-89ab8260-8926-458a-bb71-14f7ff568060.png)

**Comment by babanomania** [comment]
or think around the lines of adding an weekly heatmap, that shows the device presence for a week, a little bit of calculation might be needed to achieve this

**Comment by DartLazer** [comment]
> this is a brilliant idea, you can also add a date-range input

Nice i like both ideas. The heatmap too!

**Comment by DartLazer** [comment]
Implemented in 5ddebef7b98e6d1e91c081cb217a306148a93f18

**Comment by babanomania** [comment]
that is very fast @DartLazer
