### ISSUE TITLE
Feature Request: Add optional notifications for new devices

### ISSUE THREAD

**Issue by whur** [DartLazer/WhoIsHomeUI#14]
It would be nice to have an optional notification for a new device showing up. Once everything is setup it seems like a good way to track any rogue devices without necessarily reviewing the timeline log ui.

**Comment by DartLazer** [comment]
Nice idea! Will implement this soon!

**Comment by DartLazer** [comment]
Added in 93e233ade610c0c67ff26c9193f945b01ae341d7 @whur 

![afbeelding](https://user-images.githubusercontent.com/71255041/185063503-b2f6cadf-827e-4e48-9168-600bc261fc34.png)
