### ISSUE TITLE
Need an App Icon

### ISSUE THREAD

**Issue by babanomania** [DartLazer/WhoIsHomeUI#16]
I usually check this application from mobile, but when I add this as an homescreen icon it is added as a bookmark

![Screenshot_20220818-111250.jpg](https://user-images.githubusercontent.com/1607149/185394478-2dbbd706-8b5d-438b-8946-14035a8d72c3.jpg)

We can add an manifest to the application to make it look like an App with a proper icon, when somebody does 'add to homescreen' from browser 

Below is a little documentation with sample manifest files
https://web.dev/add-manifest/

**Comment by babanomania** [comment]
@spandan13 @DartLazer checkout the below branch for the changes related to the new logo

https://github.com/babanomania/WhoIsHomeUI/tree/added-a-manifest

**Comment by babanomania** [comment]
![Screenshot_20220820-110219.jpg](https://user-images.githubusercontent.com/1607149/185730567-2a0b088d-4638-4e67-ad6e-5f331e5fbe92.jpg)

New logo looks good

**Comment by babanomania** [comment]
but since this has white background, does not look good with the header bar in the main application

**Comment by DartLazer** [comment]
> but since this has white background, does not look good with the header bar in the main application

Maybe a seperate one for the header bar that's transparent?  @spandan13

**Comment by spandan13** [comment]
> but since this has white background, does not look good with the header bar in the main application
Uploaded transparent and also black background versions below @babanomania 
[Google Drive](https://drive.google.com/drive/folders/1i3BkAdrrIm5hd-UaIIKUjziAY8eDPX3S?usp=sharing)

**Comment by babanomania** [comment]
![image](https://user-images.githubusercontent.com/1607149/185742406-111da479-d3d9-4c55-a456-7485491d5b7f.png)

![image](https://user-images.githubusercontent.com/1607149/185742430-15f0b50f-422b-4eba-9909-58684f0332cd.png)

now the image has been updated in navbar also, check this branch @DartLazer @spandan13 

https://github.com/babanomania/WhoIsHomeUI/tree/added-a-manifest

**Comment by DartLazer** [comment]
I like it!  I think we can merge?

**Comment by babanomania** [comment]
Okay

**Comment by DartLazer** [comment]
Thanks a lot for the nice work again @babanomania @spandan13

**Comment by babanomania** [comment]
@spandan13 good work, thanks for the logo

**Comment by spandan13** [comment]
@babanomania Thanks for your time and efforts! I love the app even more now! @DartLazer
