### ISSUE TITLE
Does not work along Pi-Hole

### ISSUE THREAD

**Issue by wasee292** [DartLazer/WhoIsHomeUI#2]
After the installation and setup, I tried accessing the web page using my-raspberrypi-ip:8000.
Looks like Pi-Hole uses the same (default) port 8000 and Pi-Hole redirects to elsewhere.

Using some other port might solve the issue. Necessary change can be made in line 7 of docker-compose.yml file.

If there is some downside of the above suggested change, please let me know.

**Comment by DartLazer** [comment]
Good one! 
Would be useful to either put it in the documentation or assign a nonstandard port, specific to this tool, to it.

Any suggestions?

**Comment by wasee292** [comment]
57759
