### ISSUE TITLE
Personal Data Leakage

### ISSUE THREAD

**Issue by babanomania** [DartLazer/WhoIsHomeUI#22]
the below file contains some devices names for some network, i think this should not be posted on a public repository

```bash
wget https://github.com/DartLazer/WhoIsHomeUI/blob/main/mysite/whoishome/datastorage?raw=true
cat *datastorage*
```

**Comment by DartLazer** [comment]
Weird luckily nothing important in there. I cant even see it in the browser, how do we get it away?

**Comment by babanomania** [comment]
download it on the raspberry pi and then cat the file

**Comment by babanomania** [comment]
> Weird luckily nothing important in there. I cant even see it in the browser, how do we get it away?

Can we remove the file from git and add it to gitignore

**Comment by DartLazer** [comment]
Yes no time today and tomorrow if you create pull request i can accept.  Same for the curl thing if you tested it and works
