### ISSUE TITLE
Request: Authentication

### ISSUE THREAD

**Issue by whur** [DartLazer/WhoIsHomeUI#26]
Is there a way to setup an authentication for this? I saw django has an admin panel on /admin but I am unsure if the super user is set and what password it would be set to.

**Comment by DartLazer** [comment]
Good idea! Maybe a setting you could switch on and off which would enable password authentication on the whole app?

Is that what you're thinking of?

**Comment by whur** [comment]
That would work. I assume django handles this from my quick documentation look up of it.

**Comment by DartLazer** [comment]
Yes it will be very easy to implement I'll try to build and upload it this week. 😁 I had been playing with this idea before

**Comment by DartLazer** [comment]
If you want to help out you're also welcome to do so! I've implemented this on various projects already hence why it will be a quick fix for me! You're also welcome to help out on other items on the to do list in discussions!

**Comment by whur** [comment]
I'm not a coder, I just hack together what I need to work. Sorry I can't contribute meaningfully in that regard.

**Comment by DartLazer** [comment]
No worries! I'll look into it!

**Comment by DartLazer** [comment]
Added in f70c19f0d207c1011ac46c04e52771f978cfa08c 

Got busy with work on some other projects hence the slight delay!
