### ISSUE TITLE
Adding alternative ways for notifications 

### ISSUE THREAD

**Issue by nturneruk** [DartLazer/WhoIsHomeUI#9]
A good feature would be having alternative ways to be notified when someone leaves/arrives home - such as SMS, Telegram etc.!

**Comment by DartLazer** [comment]
Discord notifications have just been added in the latest update @nturneruk !

**Comment by babanomania** [comment]
This is awesome, can wait for to test this tonight

**Comment by babanomania** [comment]
@DartLazer the time comming with the discord messages seems to be in UTC

**Comment by DartLazer** [comment]
> @DartLazer the time comming with the discord messages seems to be in UTC

Fixed in 8f04c52807e20e1684effcd72e54cb4d06bdac8a
